{{- range $name, $app := .Values.applications }}
{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: showbiz-{{ $name }}
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: showbiz
    app.kubernetes.io/managed-by: app-of-apps
    showbiz.io/environment: {{ $.Values.environment }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ $.Values.targetRevision }}
    path: helm/charts/showbiz-app
    helm:
      valueFiles:
        - ../../../values/{{ $.Values.environment }}/{{ $name }}/values.yaml
  destination:
    server: {{ $.Values.destination.server }}
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}
